//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCDatatableApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int CustomersID { get; set; }
        public string Name { get; set; }
        public string City { get; set; }
        public string Postal { get; set; }
        public string Email { get; set; }
        public string Company { get; set; }
        public string Account { get; set; }
        public string CreditCard { get; set; }
    }
}
